### PR TITLE
icon: add libraries.io

### PR DESCRIPTION
**Pull request by Mouvedia**
https://libraries.io/

### CODE REVIEW

**Comment by amio** [comment]
Thanks for this PR!
While I forgot to update docs that, icons has been moved to a standalone lib [badgen-icons](https://github.com/badgen/badgen-icons). My bad 😅

I'll add this icon to badgen-icons and finish the docs changes soon.
Thanks again! @Mouvedia

**Comment by Mouvedia** [comment]
badgen/badgen-icons@0cde473bb0545852357611f890c90c934c9d47da

I just tried https://badgen.net/badge/foo/bar?icon=libraries, it doesn't work.
Where can I find the new API?

**Comment by Mouvedia** [comment]
badgen/badgen-icons@0cde473bb0545852357611f890c90c934c9d47da

I just tried https://badgen.net/badge/foo/bar?icon=libraries, it doesn't work.
@amio Do you have an example URL?

**Comment by amio** [comment]
It's not deployed yet, the icon looks slightly smaller than other icons on badge, it might need some adjustments manually.

You can have a preview here https://badgen-service-uljyowptmn.now.sh/

When it shows alone, it looks fine though

**Comment by Mouvedia** [comment]
I took the SVG directly from [their logo](https://libraries.io/assets/logo-81a987a6228bd0482a3b741ec729bedbb3963acd2c02944479557abf63c54a75.svg).

> 

It looks good to me.

> it might need some adjustments manually.

Ill leave that to you ;)

**Comment by amio** [comment]
Yep I'll take the rest.

**Comment by Mouvedia** [comment]
> It's not deployed yet

Without the now bot where should I check?

**Comment by amio** [comment]
It's landed now :D

https://badgen.net/badge//libraries?icon=libraries

**Pull request closed without merging**
