### PR TITLE
New index page

### PR DESCRIPTION
**Pull request by amio**
That [index.md](https://github.com/amio/badgen-service/blob/dca83facc83927e7ad6f4cd7678d6db53562bab6/libs/index.md) is horrible for editing 🙀

This PR create a new index page:

- Use `lit-html` to generate examples section.
- Move "Available query params" to first screen.
- Add "Available icons" section.

Preview at https://badgen-new-index.now.sh

### TODO

- [x] Complete live badge example list.
- [ ] Link to live badge's own doc page (e.g. [/docs/packagephobia](https://badgen.net/docs/packagephobia))

### CODE REVIEW

**Comment by amio** [comment]
About the icon example, I thought about some options:

1. 
2. 
3. 
4. 
5. 

Any more advices?

(3) seems best but it has an extra 4px space on right side of icon. This space could only get removed through badgen library, but I don't add this burden to badgen library just for a nicer icon example.

**Comment by olstenlarck** [comment]
A lot better index, yeah! :sparkles: 

I don't understanda that https://github.com/amio/badgen-service/pull/43#issuecomment-408451123

**Comment by olstenlarck** [comment]
Btw, the section names, could be headers with `#` so you can `https://badgen.net#github`

like here https://tunnckocore.com/#automation

**Comment by amio** [comment]
About the icon example, I mean choose what label/status to showcase the icons, like:

   ...

or

   ...

etc.

**Pull request merged**
