### PR TITLE
fix: add @AirBnB logo

### PR DESCRIPTION
**Pull request by olstenlarck**
add @AirBnB logo

### CODE REVIEW

**Comment by olstenlarck** [comment]
Why not just add all of the SimpleIcons? ;d

**Comment by amio** [comment]
Icons in `simple-icons` doesn't have default color, and some are colored by `fill` attribute, some by `stroke`. Auto processing (add color attr) works not so well, so I removed it, decide every icon need to get reviewed before it's available.

**Comment by olstenlarck** [comment]
Right.

Is airbnb's okey for merge?

**Comment by amio** [comment]
This one need a `fill="#FFF"` too 😂

After [svgomg](https://jakearchibald.github.io/svgomg/)ed:
```xml
<svg xmlns="http://www.w3.org/2000/svg" fill="#FFF" viewBox="0 0 24 24">
  <path d="M12 18.3a11.3 11.3 0 0 1-2.4-4.5c-.3-1-.2-1.8.3-2.5s1.2-1 2.1-1 1.6.3 2.1 1 .6 1.5.3 2.5c-.3 1.3-1 2.8-2.4 4.5zm9.6 1.1c-.2 1.3-1 2.3-2.2 2.8-2.3 1-4.5-.6-6.4-2.7 3.2-4 3.7-7 2.4-9-.8-1.2-2-1.7-3.4-1.7-3 0-4.6 2.5-4 5.4.4 1.5 1.4 3.3 3 5.3-1 1-2 1.8-2.7 2.3-.7.4-1.3.6-1.9.6-2.6.4-4.7-2.2-3.8-4.8l.9-2c1.4-3.2 3.2-6.8 5.3-10.9l.6-1.2c.4-.8.6-1.2 1.3-1.6.4-.3.8-.4 1.3-.4 1 0 1.7.6 2 1l.6 1 .5 1 .1.2 5.3 10.8.6 1.3.3.7c.2.7.3 1.3.2 1.9zm1.2-2.4l-.9-2v-.1c-1.9-4-3.6-7.6-5.3-10.8l-.1-.2C15.3 1.5 14.5 0 12 0 9.6 0 8.5 1.7 7.5 3.9l-.1.2C5.7 7.3 4 10.9 2 14.9l-.6 1.3-.3.8A5.1 5.1 0 0 0 6 24H6.6c1.8-.2 3.6-1.4 5.4-3.4 1.8 2 3.6 3.2 5.4 3.4h.6c3.4 0 6.2-3.3 4.8-7z"/>
</svg>
```

**Comment by olstenlarck** [comment]
Aha. I'll update it.

**Pull request merged**
