### PR TITLE
feat(github): add statuses badge

### LINKED ISSUE #157: Feature request: Github Commit/branch Status
https://developer.github.com/v3/repos/statuses/

```
badgen.net/github/status/babel/babel
badgen.net/github/status/babel/babel/[branch | commit | ref]
badgen.net/github/status/babel/babel/foobar
badgen.net/github/status/babel/babel/35h5jkh56k
```

All this will play well with the new Now + Github enhancement. You will just point to the github status to have "build status badge".

### PR DESCRIPTION
**Pull request by tunnckoCore**
yeaaah, closes #157 :heart_eyes: 

There should probably also have and for each status, but.. not so needed.

This allows to totally move to "Now CI" (as i call it):
https://zeit.co/blog/every-push-now

### CODE REVIEW

**Comment by tunnckoCore** [comment]
https://badgen-service-tbrtjbgeuw.now.sh/github/status/amio/badgen-service



https://badgen-service-tbrtjbgeuw.now.sh/github/status/tunnckoCore/badgen-service/github-status




https://badgen-service-tbrtjbgeuw.now.sh/github/status/tunnckoCore/foobar/84d12681ee061?label=build

**Comment by amio** [comment]
Awesome! As the url schema, how about `github/status-<service>`?

```
/github/status/babel/babel
/github/status-travis/babel/babel
/github/status-codecov/babel/babel
```

**Comment by tunnckoCore** [comment]
Make sense, yea. But let's be another PR.

**Comment by amio** [comment]
Oops, I was mean to discard changes in package-lock.json, but deleted the file instead. I remember it's discard button formerly.

@tunnckoCore Can you remove that change?

**Comment by arunoda** [comment]
Hey @amio @tunnckoCore sorry for hijack this PR.
I'm from ZEIT and I can see the deployment we automatically did was deleted.
I am talking about this one: https://zeit.co/github/deployment?deploymentId=jRiyXCbF385sPBAGcW5KvKm9

Have you authorized that?

**Comment by amio** [comment]
@arunoda Thanks for reaching out! Currently the deployment needs some env vars I specified in npm scripts ([`deploy`](https://github.com/amio/badgen-service/blob/35dedfab8f0bbe05cef3d88c83c11ac4a16898aa/package.json#L16)), so the auto aliased deployment is broken. I wish people could deploy a instance simply with 'now deploy foo/bar' without providing env vars (required by some features), that's the reason I put env in scripts instead of now.json.

There might be some solutions for this use case, either:
- Let user disable auto aliasing in now.json
- Auto deploy with `now-deploy` script when it's presented.

What do you think?

**Comment by arunoda** [comment]
@amio you can deploy with env vars. For that use [now secrets](https://zeit.co/docs/getting-started/secrets)

Our GitHub integration handles them pretty well too: https://zeit.co/blog/deploy-github-forks

**Comment by amio** [comment]
@arunoda I use to put secret requirements in `now.json` but later [move](https://github.com/amio/badgen-service/commit/211e3015fac85da3ed741c9d5a11d45c0e6bbc49#comments) them to npm scripts, for a simpler `now amio/badgen-service` usage.

**Comment by arunoda** [comment]
We recommend to use secrets in `now.json` and handle them in that way.
But of course, you can use anyway as you wish.

> Let user disable auto aliasing in now.json
This is already doable. Change the `now.json` like this:

```
{
   "github": {
     "autoAlias": false
   }
}
```

> Auto deploy with now-deploy script when it's presented.

Then this is only for Node.js apps. We want to make it universal for all the apps. But I got your point.

**Comment by amio** [comment]
Thanks @arunoda! Nice to have an universal customizable deploy command 🎉

**Comment by tunnckoCore** [comment]
@arunoda regarding https://github.com/amio/badgen-service/pull/158#issuecomment-422252464 ... probably because i was cleaning up my profile ;d Was not sure which one was the latest and just picked one ;d

**Comment by amio** [comment]
This PR is merged by #161

**Comment by styfle** [comment]
@arunoda You should add that `autoAlias` flag to the zeit docs. I checked the alias docs and the github docs and neither mention it.

**Pull request closed without merging**
