### PR TITLE
refactor: find-my-way => micro + micro-fork

### PR DESCRIPTION
**Pull request by amio**
and nodemon => micro-dev
and support query params: style, label, emoji, list

Regarding https://github.com/amio/badgen-service/issues/10#issuecomment-406813669

### Preview

https://badgen-service-jczedbqvoc.now.sh/
https://badgen-service-jczedbqvoc.now.sh/badge/chat/gitter/purple?style=flat&label=asdf

### CODE REVIEW

**Comment by olstenlarck** [comment]
Hm or not. Yea it works anyway i think.

**Comment by olstenlarck** [comment]
When will go live?

**Comment by amio** [comment]
Curious, what badge/query are you going to use?

**Comment by olstenlarck** [comment]
I already started replacing all the badges to Badgen ;]]

As about the query usage. I don't like `npm | v1.2.3` and `release | v1.2.3`, so i make them `npm version | v1.2.3` and `github release | v1.2.3` :D Self preference, it's more clear and explicit. (https://github.com/olstenlarck/eslint-config-xaxa)

> It's live now :D

Why it's not automattic after the merge? Why is that Now deployment Github App then?

**Comment by amio** [comment]
We need a reliable test suite before making deployment automatically.

Now's Github App keep complaining in almost every PR:

> Since this Pull Request originated from a forked repository, Now cannot deploy it as there are potential security risks.

So I turn it off, at least for now. 😔

**Pull request merged**
