### PR TITLE
Update packagist service domain

### PR DESCRIPTION
**Pull request by vinkla**
The Packagist metadata API has been updated: https://packagist.org/apidoc#get-package-data

### CODE REVIEW

**Comment by amio** [comment]
Looks good 👍

I see the new endpoint is `https://repo.packagist.org/packages/...` other than `https://repo.packagist.org/p/...` in the [document](https://repo.packagist.org/p/monolog/monolog.json), is it an undocumented feature?

**Comment by vinkla** [comment]
Nah, you're are correct. I didn't read the documentation careful enough.

**Comment by amio** [comment]
It's a little strange, actually the undocumented `https://repo.packagist.org/packages/` works fine, while documented `https://repo.packagist.org/p/` output a different format, compare to the original endpoint `https://packagist.org/packages/` 🤯

**Comment by vinkla** [comment]
Yeah, not sure why it works that way to be honest.

**Pull request closed without merging**
